sudo: required
services:
  - docker

#building test image for running script

before_install:
 - docker build -t vikas/react-test -f ./client/Dockerfile.dev ./client

# Test cases running on test-image 

script:
 - docker run -e CI=true vikas/react-test npm test

#After test cases execution building production version of dockerImages

after_success:
 - docker build -t vikas888/multi-react ./client
 - docker build -t vikas888/multi-nginx ./nginx
 - docker build -t vikas888/multi-server ./server
 - docker build -t vikas888/multi-worker ./worker

#Login in to the Docker CLI

 - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin

#Pusing the Production Images to DOCKER_HUB

 - docker push vikas888/multi-react
 - docker push vikas888/multi-nginx
 - docker push vikas888/multi-server
 - docker push vikas888/multi-worker 


deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-619038546570
  bucket_path: multi-docker
  on:
    branch: master
  
  access_key_id:
    secure: $AWS_ACCESS_ID
  secret_access_key:
    secure: $AWS_SECRET_KEY

# MultiDocker-env.y8vxqimmjm.us-east-2.elasticbeanstalk.com
